# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("stream.proto", :syntax => :proto3) do
    add_message "stream.TrackRequest" do
      optional :idTrack, :string, 1
      optional :quality, :enum, 2, "stream.TrackRequest.Quality"
    end
    add_enum "stream.TrackRequest.Quality" do
      value :HIGH, 0
      value :MIDDLE, 1
      value :SHORT, 2
    end
    add_message "stream.TrackSample" do
      optional :audio, :bytes, 1
    end
  end
end

module Stream
  TrackRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("stream.TrackRequest").msgclass
  TrackRequest::Quality = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("stream.TrackRequest.Quality").enummodule
  TrackSample = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("stream.TrackSample").msgclass
end
